@proxyUrl = https://testnet-api.elrond.com
@observerUrl = http://localhost:8080

###

// Get heartbeat status
GET {{proxyUrl}}/node/heartbeatstatus HTTP/1.1

###

// Observer: Get heartbeat status
GET {{observerUrl}}/node/heartbeatstatus HTTP/1.1

###

// Observer: Get statistics
GET {{observerUrl}}/node/statistics HTTP/1.1

###

// Observer: Get p2p status
GET {{observerUrl}}/node/p2pstatus HTTP/1.1

###

// Observer: Get peer info
GET {{observerUrl}}/node/peerinfo HTTP/1.1
