@baseUrl = http://localhost:7950
@exampleTx = fa8195bae93d4609a6fc5972a7a6176feece39a6c4821acae2276701aee12fb0


// Send transaction
POST {{baseUrl}}/transaction/send HTTP/1.1
Content-Type: application/json

{
    "nonce": 42,
    "value": "100000000000000000",
    "receiver": "erd1cux02zersde0l7hhklzhywcxk4u9n4py5tdxyx7vrvhnza2r4gmq4vw35r",
    "sender": "erd1asuj9sdzj0yl93fnspw5ndttdf6qz02t9hw8dnnuv2cnl0muwwhsr7zv84",
    "gasPrice": 1000000000,
    "gasLimit": 70000,
    "data": "Zm9vZCBmb3IgY2F0cw==",
    "chainID": "v1.0.147",
    "version": 1,
    "signature": "12d6866b1c01d6b6e25e0582ef08c6c36242a0c851f43972866ae46d904c15da619c393e2b34b51b3cdbb9ea02174dc0fd428048e75ded73edd4d2b136655b0c"
}

// Send multiple transactions
POST {{baseUrl}}/transaction/send-multiple HTTP/1.1
Content-Type: application/json

[
    {
        "nonce": 42,
        "value": "100000000000000000",
        "receiver": "erd1cux02zersde0l7hhklzhywcxk4u9n4py5tdxyx7vrvhnza2r4gmq4vw35r",
        "sender": "erd15z2fqg03lwhkcgjtu465nwwz7l5xlasyscf6sdlwejs5vea30gdqcjd8ez",
        "gasPrice": 1000000000,
        "gasLimit": 70000,
        "data": "Zm9vZCBmb3IgY2F0cw==",
        "chainID": "v1.0.147",
        "version": 1,
        "signature": "c5974c1015e97b016920237e2f6f95dfa6987a583b02821bbaecf1c160f4bb2e87f28375a8adc9eccee42f35bc65fc45cf53efbcd70c955399b2dc619aa0270e"
    },
    {
        "nonce": 43,
        "value": "100000000000000000",
        "receiver": "erd1cux02zersde0l7hhklzhywcxk4u9n4py5tdxyx7vrvhnza2r4gmq4vw35r",
        "sender": "erd1yg3e7m99kllytmwx05rgcr03xywjkhjercj5u7stfmvm9q26l4us4rf48k",
        "gasPrice": 1000000000,
        "gasLimit": 70000,
        "data": "Zm9vZCBmb3IgY2F0cw==",
        "chainID": "v1.0.147",
        "version": 1,
        "signature": "7f307203bb16f9713aa0d440c6f98e251977497aa280dc42867b8137033caf3ec41fcb903bb4dff74860aa23f13b00627d041ac4099aac88f6568a4978264206"
    }
]

###

// Estimate cost of transaction
POST {{baseUrl}}/transaction/cost HTTP/1.1
Content-Type: application/json

{
    "value": "100000",
    "sender": "erd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz",
    "receiver": "erd188nydpkagtpwvfklkl2tn0w6g40zdxkwfgwpjqc2a2m2n7ne9g8q2t22sr",
    "data": "this is an example",
    "chainID": "v1.0.141",
    "version": 1
}

###

// Get transaction
GET {{baseUrl}}/transaction/{{exampleTx}} HTTP/1.1

###

// Get transaction status
GET {{baseUrl}}/transaction/{{exampleTx}}/status HTTP/1.1

###

// Simulate transactions
POST {{baseUrl}}/transaction/simulate HTTP/1.1
Content-Type: application/json

{
    "nonce": 5,
    "value": "0",
    "receiver": "erd1spyavw0956vq68xj8y4tenjpq2wd5a9p2c6j8gsz7ztyrnpxrruqzu66jx",
    "sender": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "gasPrice": 1000000000,
    "gasLimit": 70000,
    "data": "SGVsbG8sIFdvcmxk",
    "chainID": "local-testnet",
    "version": 1,
    "signature": "ae02374458e6b50f440e98da8ac38f491c86aab67ad67d5d93cd90d03ed9e4c7c2bc9840ce64cd11c3336b1d6fe93d7b9196e60eebb65ff55457df0e2da3cb0c"
}